import type { OfferItem } from './views/HomeView';

export const mockOffers: OfferItem[] = [
  {
    product: {
      product_key: 'prod_001',
      product_id: 'ica_101',
      name: 'Standardmjölk 3%',
      brand: 'Arla',
      pack_size: '1L',
      country_of_origin: 'Sverige',
      unit: 'l',
      product_type: 'dairy',
      is_alcohol: false,
      first_seen_at: '2024-01-15T10:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    store: {
      store_id: 'store_001',
      source_store_catalog_id: 'ica_maxi_001',
      store_name: 'ICA Maxi',
      city: 'Stockholm',
      zip_code: '11122',
      street: 'Storgatan 1',
      area: 'Södermalm',
      slug: 'ica-maxi-stockholm',
      store_format: 'maxi',
      lat: 59.3293,
      lon: 18.0686,
      delivery_methods: ['pickup', 'delivery'],
      first_seen_at: '2024-01-01T00:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    currentPrice: {
      store_id: 'store_001',
      product_key: 'prod_001',
      run_id: 'run_2024_001',
      observed_at: new Date().toISOString(),
      price: 16.95,
      promo_price: 12.90,
      unit_price: 16.95,
      promo_unit_price: 12.90,
      currency: 'SEK',
      available: true
    }
  },
  {
    product: {
      product_key: 'prod_002',
      product_id: 'coop_202',
      name: 'Ekologiskt Smör',
      brand: 'Bregott',
      pack_size: '500g',
      country_of_origin: 'Sverige',
      unit: 'kg',
      product_type: 'dairy',
      is_alcohol: false,
      first_seen_at: '2024-01-10T08:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    store: {
      store_id: 'store_002',
      source_store_catalog_id: 'coop_002',
      store_name: 'Coop',
      city: 'Göteborg',
      zip_code: '41101',
      street: 'Avenyn 10',
      area: 'Centrum',
      slug: 'coop-goteborg-centrum',
      store_format: 'stora',
      lat: 57.7089,
      lon: 11.9746,
      delivery_methods: ['pickup'],
      first_seen_at: '2024-01-01T00:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    currentPrice: {
      store_id: 'store_002',
      product_key: 'prod_002',
      run_id: 'run_2024_001',
      observed_at: new Date().toISOString(),
      price: 54.90,
      promo_price: 39.90,
      unit_price: 109.80,
      promo_unit_price: 79.80,
      currency: 'SEK',
      available: true
    }
  },
  {
    product: {
      product_key: 'prod_003',
      product_id: 'willys_303',
      name: 'Fullkornspasta Penne',
      brand: 'Barilla',
      pack_size: '500g',
      country_of_origin: 'Italien',
      unit: 'kg',
      product_type: 'pasta',
      is_alcohol: false,
      first_seen_at: '2024-02-01T12:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    store: {
      store_id: 'store_003',
      source_store_catalog_id: 'willys_003',
      store_name: 'Willys',
      city: 'Malmö',
      zip_code: '21119',
      street: 'Triangeln 5',
      area: 'Centrum',
      slug: 'willys-malmo-triangeln',
      store_format: 'standard',
      lat: 55.5964,
      lon: 13.0015,
      delivery_methods: [],
      first_seen_at: '2024-01-01T00:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    currentPrice: {
      store_id: 'store_003',
      product_key: 'prod_003',
      run_id: 'run_2024_001',
      observed_at: new Date().toISOString(),
      price: 24.90,
      promo_price: null,
      unit_price: 49.80,
      promo_unit_price: null,
      currency: 'SEK',
      available: true
    }
  },
  {
    product: {
      product_key: 'prod_004',
      product_id: 'hemkop_404',
      name: 'Bryggkaffe Mörkrost',
      brand: 'Gevalia',
      pack_size: '450g',
      country_of_origin: 'Brasilien',
      unit: 'kg',
      product_type: 'coffee',
      is_alcohol: false,
      first_seen_at: '2024-01-05T09:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    store: {
      store_id: 'store_004',
      source_store_catalog_id: 'hemkop_004',
      store_name: 'Hemköp',
      city: 'Uppsala',
      zip_code: '75320',
      street: 'Dragarbrunnsgatan 12',
      area: 'Centrum',
      slug: 'hemkop-uppsala',
      store_format: 'standard',
      lat: 59.8586,
      lon: 17.6389,
      delivery_methods: ['delivery'],
      first_seen_at: '2024-01-01T00:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    currentPrice: {
      store_id: 'store_004',
      product_key: 'prod_004',
      run_id: 'run_2024_001',
      observed_at: new Date().toISOString(),
      price: 69.90,
      promo_price: 49.90,
      unit_price: 155.33,
      promo_unit_price: 110.89,
      currency: 'SEK',
      available: true
    }
  },
  {
    product: {
      product_key: 'prod_005',
      product_id: 'ica_505',
      name: 'Bananer',
      brand: 'Chiquita',
      pack_size: '1kg',
      country_of_origin: 'Costa Rica',
      unit: 'kg',
      product_type: 'fruit',
      is_alcohol: false,
      first_seen_at: '2024-01-01T00:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    store: {
      store_id: 'store_001',
      source_store_catalog_id: 'ica_maxi_001',
      store_name: 'ICA Maxi',
      city: 'Stockholm',
      zip_code: '11122',
      street: 'Storgatan 1',
      area: 'Södermalm',
      slug: 'ica-maxi-stockholm',
      store_format: 'maxi',
      lat: 59.3293,
      lon: 18.0686,
      delivery_methods: ['pickup', 'delivery'],
      first_seen_at: '2024-01-01T00:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    currentPrice: {
      store_id: 'store_001',
      product_key: 'prod_005',
      run_id: 'run_2024_001',
      observed_at: new Date().toISOString(),
      price: 19.90,
      promo_price: null,
      unit_price: 19.90,
      promo_unit_price: null,
      currency: 'SEK',
      available: true
    }
  },
  {
    product: {
      product_key: 'prod_006',
      product_id: 'coop_606',
      name: 'Köttfärs Nöt',
      brand: 'Scan',
      pack_size: '500g',
      country_of_origin: 'Sverige',
      unit: 'kg',
      product_type: 'meat',
      is_alcohol: false,
      first_seen_at: '2024-01-12T14:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    store: {
      store_id: 'store_002',
      source_store_catalog_id: 'coop_002',
      store_name: 'Coop',
      city: 'Göteborg',
      zip_code: '41101',
      street: 'Avenyn 10',
      area: 'Centrum',
      slug: 'coop-goteborg-centrum',
      store_format: 'stora',
      lat: 57.7089,
      lon: 11.9746,
      delivery_methods: ['pickup'],
      first_seen_at: '2024-01-01T00:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    currentPrice: {
      store_id: 'store_002',
      product_key: 'prod_006',
      run_id: 'run_2024_001',
      observed_at: new Date().toISOString(),
      price: 59.90,
      promo_price: 44.90,
      unit_price: 119.80,
      promo_unit_price: 89.80,
      currency: 'SEK',
      available: true
    }
  },
  {
    product: {
      product_key: 'prod_007',
      product_id: 'willys_707',
      name: 'Isländsk Skyr Naturell',
      brand: 'Siggi\'s',
      pack_size: '450g',
      country_of_origin: 'Island',
      unit: 'kg',
      product_type: 'dairy',
      is_alcohol: false,
      first_seen_at: '2024-02-10T11:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    store: {
      store_id: 'store_003',
      source_store_catalog_id: 'willys_003',
      store_name: 'Willys',
      city: 'Malmö',
      zip_code: '21119',
      street: 'Triangeln 5',
      area: 'Centrum',
      slug: 'willys-malmo-triangeln',
      store_format: 'standard',
      lat: 55.5964,
      lon: 13.0015,
      delivery_methods: [],
      first_seen_at: '2024-01-01T00:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    currentPrice: {
      store_id: 'store_003',
      product_key: 'prod_007',
      run_id: 'run_2024_001',
      observed_at: new Date().toISOString(),
      price: 32.90,
      promo_price: null,
      unit_price: 73.11,
      promo_unit_price: null,
      currency: 'SEK',
      available: true
    }
  },
  {
    product: {
      product_key: 'prod_008',
      product_id: 'hemkop_808',
      name: 'Havregryn Stora',
      brand: 'AXA',
      pack_size: '1.5kg',
      country_of_origin: 'Sverige',
      unit: 'kg',
      product_type: 'cereals',
      is_alcohol: false,
      first_seen_at: '2024-01-20T07:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    store: {
      store_id: 'store_004',
      source_store_catalog_id: 'hemkop_004',
      store_name: 'Hemköp',
      city: 'Uppsala',
      zip_code: '75320',
      street: 'Dragarbrunnsgatan 12',
      area: 'Centrum',
      slug: 'hemkop-uppsala',
      store_format: 'standard',
      lat: 59.8586,
      lon: 17.6389,
      delivery_methods: ['delivery'],
      first_seen_at: '2024-01-01T00:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    currentPrice: {
      store_id: 'store_004',
      product_key: 'prod_008',
      run_id: 'run_2024_001',
      observed_at: new Date().toISOString(),
      price: 34.90,
      promo_price: 24.90,
      unit_price: 23.27,
      promo_unit_price: 16.60,
      currency: 'SEK',
      available: true
    }
  },
  {
    product: {
      product_key: 'prod_009',
      product_id: 'ica_909',
      name: 'Krossade Tomater',
      brand: 'Mutti',
      pack_size: '400g',
      country_of_origin: 'Italien',
      unit: 'kg',
      product_type: 'canned',
      is_alcohol: false,
      first_seen_at: '2024-01-08T15:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    store: {
      store_id: 'store_001',
      source_store_catalog_id: 'ica_maxi_001',
      store_name: 'ICA Maxi',
      city: 'Stockholm',
      zip_code: '11122',
      street: 'Storgatan 1',
      area: 'Södermalm',
      slug: 'ica-maxi-stockholm',
      store_format: 'maxi',
      lat: 59.3293,
      lon: 18.0686,
      delivery_methods: ['pickup', 'delivery'],
      first_seen_at: '2024-01-01T00:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    currentPrice: {
      store_id: 'store_001',
      product_key: 'prod_009',
      run_id: 'run_2024_001',
      observed_at: new Date().toISOString(),
      price: 18.90,
      promo_price: 14.90,
      unit_price: 47.25,
      promo_unit_price: 37.25,
      currency: 'SEK',
      available: true
    }
  },
  {
    product: {
      product_key: 'prod_010',
      product_id: 'coop_1010',
      name: 'Lax Filé Färsk',
      brand: 'Klädesholmen',
      pack_size: '400g',
      country_of_origin: 'Norge',
      unit: 'kg',
      product_type: 'fish',
      is_alcohol: false,
      first_seen_at: '2024-02-05T10:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    store: {
      store_id: 'store_002',
      source_store_catalog_id: 'coop_002',
      store_name: 'Coop',
      city: 'Göteborg',
      zip_code: '41101',
      street: 'Avenyn 10',
      area: 'Centrum',
      slug: 'coop-goteborg-centrum',
      store_format: 'stora',
      lat: 57.7089,
      lon: 11.9746,
      delivery_methods: ['pickup'],
      first_seen_at: '2024-01-01T00:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    currentPrice: {
      store_id: 'store_002',
      product_key: 'prod_010',
      run_id: 'run_2024_001',
      observed_at: new Date().toISOString(),
      price: 89.90,
      promo_price: null,
      unit_price: 224.75,
      promo_unit_price: null,
      currency: 'SEK',
      available: true
    }
  },
  {
    product: {
      product_key: 'prod_011',
      product_id: 'willys_1111',
      name: 'Ägg Frigående M',
      brand: 'Kronägg',
      pack_size: '12st',
      country_of_origin: 'Sverige',
      unit: 'st',
      product_type: 'eggs',
      is_alcohol: false,
      first_seen_at: '2024-01-02T06:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    store: {
      store_id: 'store_003',
      source_store_catalog_id: 'willys_003',
      store_name: 'Willys',
      city: 'Malmö',
      zip_code: '21119',
      street: 'Triangeln 5',
      area: 'Centrum',
      slug: 'willys-malmo-triangeln',
      store_format: 'standard',
      lat: 55.5964,
      lon: 13.0015,
      delivery_methods: [],
      first_seen_at: '2024-01-01T00:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    currentPrice: {
      store_id: 'store_003',
      product_key: 'prod_011',
      run_id: 'run_2024_001',
      observed_at: new Date().toISOString(),
      price: 42.90,
      promo_price: 34.90,
      unit_price: 3.58,
      promo_unit_price: 2.91,
      currency: 'SEK',
      available: true
    }
  },
  {
    product: {
      product_key: 'prod_012',
      product_id: 'hemkop_1212',
      name: 'Apelsinjuice Färskpressad',
      brand: 'Tropicana',
      pack_size: '900ml',
      country_of_origin: 'USA',
      unit: 'l',
      product_type: 'juice',
      is_alcohol: false,
      first_seen_at: '2024-01-18T13:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    store: {
      store_id: 'store_004',
      source_store_catalog_id: 'hemkop_004',
      store_name: 'Hemköp',
      city: 'Uppsala',
      zip_code: '75320',
      street: 'Dragarbrunnsgatan 12',
      area: 'Centrum',
      slug: 'hemkop-uppsala',
      store_format: 'standard',
      lat: 59.8586,
      lon: 17.6389,
      delivery_methods: ['delivery'],
      first_seen_at: '2024-01-01T00:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    currentPrice: {
      store_id: 'store_004',
      product_key: 'prod_012',
      run_id: 'run_2024_001',
      observed_at: new Date().toISOString(),
      price: 29.90,
      promo_price: null,
      unit_price: 33.22,
      promo_unit_price: null,
      currency: 'SEK',
      available: true
    }
  },
  {
    product: {
      product_key: 'prod_013',
      product_id: 'ica_1313',
      name: 'Ris Basmati',
      brand: 'Uncle Bens',
      pack_size: '1kg',
      country_of_origin: 'Indien',
      unit: 'kg',
      product_type: 'rice',
      is_alcohol: false,
      first_seen_at: '2024-01-25T08:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    store: {
      store_id: 'store_001',
      source_store_catalog_id: 'ica_maxi_001',
      store_name: 'ICA Maxi',
      city: 'Stockholm',
      zip_code: '11122',
      street: 'Storgatan 1',
      area: 'Södermalm',
      slug: 'ica-maxi-stockholm',
      store_format: 'maxi',
      lat: 59.3293,
      lon: 18.0686,
      delivery_methods: ['pickup', 'delivery'],
      first_seen_at: '2024-01-01T00:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    currentPrice: {
      store_id: 'store_001',
      product_key: 'prod_013',
      run_id: 'run_2024_001',
      observed_at: new Date().toISOString(),
      price: 39.90,
      promo_price: 29.90,
      unit_price: 39.90,
      promo_unit_price: 29.90,
      currency: 'SEK',
      available: true
    }
  },
  {
    product: {
      product_key: 'prod_014',
      product_id: 'coop_1414',
      name: 'Olivolja Extra Virgin',
      brand: 'Zeta',
      pack_size: '500ml',
      country_of_origin: 'Spanien',
      unit: 'l',
      product_type: 'oil',
      is_alcohol: false,
      first_seen_at: '2024-02-01T09:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    store: {
      store_id: 'store_002',
      source_store_catalog_id: 'coop_002',
      store_name: 'Coop',
      city: 'Göteborg',
      zip_code: '41101',
      street: 'Avenyn 10',
      area: 'Centrum',
      slug: 'coop-goteborg-centrum',
      store_format: 'stora',
      lat: 57.7089,
      lon: 11.9746,
      delivery_methods: ['pickup'],
      first_seen_at: '2024-01-01T00:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    currentPrice: {
      store_id: 'store_002',
      product_key: 'prod_014',
      run_id: 'run_2024_001',
      observed_at: new Date().toISOString(),
      price: 74.90,
      promo_price: null,
      unit_price: 149.80,
      promo_unit_price: null,
      currency: 'SEK',
      available: true
    }
  },
  {
    product: {
      product_key: 'prod_015',
      product_id: 'willys_1515',
      name: 'Falukorv Original',
      brand: 'Scan',
      pack_size: '800g',
      country_of_origin: 'Sverige',
      unit: 'kg',
      product_type: 'sausage',
      is_alcohol: false,
      first_seen_at: '2024-01-30T16:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    store: {
      store_id: 'store_003',
      source_store_catalog_id: 'willys_003',
      store_name: 'Willys',
      city: 'Malmö',
      zip_code: '21119',
      street: 'Triangeln 5',
      area: 'Centrum',
      slug: 'willys-malmo-triangeln',
      store_format: 'standard',
      lat: 55.5964,
      lon: 13.0015,
      delivery_methods: [],
      first_seen_at: '2024-01-01T00:00:00Z',
      last_seen_at: new Date().toISOString()
    },
    currentPrice: {
      store_id: 'store_003',
      product_key: 'prod_015',
      run_id: 'run_2024_001',
      observed_at: new Date().toISOString(),
      price: 32.90,
      promo_price: 24.90,
      unit_price: 41.13,
      promo_unit_price: 31.13,
      currency: 'SEK',
      available: true
    }
  }
];